# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 553d6a85f6f1174b86179ff2178fe3c4ef83075c404bd4fac3905209e8caf547f5efa2e68804dbde94f63ae01e60082ce7e4f527eb9a86b4a053013facdb148e

test:
  secret_key_base: f6fcb31326e0c0e142cd64a2e5c9ee406fed4944ceb9e231eae2722eb75a00493e3f30e9a692269b768aafc52f1563d41dd61979df808bfb32bae63ec1bdf295

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
